export const MAIN_ROUTE = '/'
export const NEWS_ROUTE = '/news'
export const ONE_NEWS_ROUTE = '/news/:id'
export const TARIFFS_ROUTE = '/tariffs'
export const AGREEMENT_ROUTE = '/agreement'
export const DOCUMENTS_ROUTE = '/documents'
export const CONTACTS_ROUTE = '/contacts'
export const LOGIN_ROUTE = '/login'
export const ADMIN_ROUTE = '/admin' //auth=true role='ADMIN'
export const PERSONAL_AREA_ROUTE = '/personalArea' //auth=true role='USER'
